server:
  port: 8080

spring:
  application:
    name: XenoShopSync

  datasource:
    url: jdbc:postgresql://localhost:5432/shopSync_db
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 953869001@smtp-brevo.com   # your email, injected from env
    password: aWSJsqrdC6NHZf27   # app password / smtp password from env
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    # Use env var JWT_SECRET in production (must be at least 256-bit for HS256).
    secret: dev-super-secret-key-1234567890-abcdefghijklmnopqrstuvwxyzletsgowithyourchicken
    issuer: waseem
    # Access token lifetime – short since we have no refresh flow
    access-minutes: 60

  cors:
    allowed-origins: http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    allow-credentials: true